
import "~/styles/globals.css";




import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/TopNav";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Loyal fan of TypeScript and Family Guy",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
        <body>
          <TopNav/>
           {children}
        </body>
      </html>
    </ClerkProvider>
  );
}